// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "406e945b-6e27-470a-a940-6257be2614a4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1675362831);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1675362811);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1675362807);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1675362861);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{c8e740a2-bc26-4663-a91a-983802cb5dc0}");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1675362801);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{68b9eeea-229f-48cd-a46c-d8d5435fff02}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1675362804);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1675362811293");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1675384411293");
user_pref("browser.search.region", "AM");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230131151141");
user_pref("browser.startup.homepage_override.mstone", "109.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1675362804);
user_pref("browser.tabs.inTitlebar", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"unified-extensions-area\"],\"currentVersion\":18,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1675362806173");
user_pref("distribution.iniFile.exists.appversion", "109.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "AM");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "8ddbcd1b335045a792d73a75dd3576e3");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230131151141");
user_pref("extensions.lastAppVersion", "109.0.1");
user_pref("extensions.lastPlatformVersion", "109.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"deba55d5-5989-477d-94b3-57671236e20c\",\"pictureinpicture@mozilla.org\":\"a6b056d5-b5ab-43b0-b2fb-504d19636652\",\"screenshots@mozilla.org\":\"c46bd891-a512-4852-860a-b323a9c458ac\",\"webcompat-reporter@mozilla.org\":\"7cd91050-f2e8-4eb9-ae6e-41d50417a132\",\"webcompat@mozilla.org\":\"4a8c0863-25d8-4aa8-b879-6f820352a14a\",\"default-theme@mozilla.org\":\"4af20f08-4607-4787-bdd3-b62313bbbd5f\",\"addons-search-detection@mozilla.com\":\"50e74f52-bf78-46c7-a993-f0991fa8e89f\",\"google@search.mozilla.org\":\"1c088c2b-a291-4dde-b45a-d8e98bed73f2\",\"amazondotcom@search.mozilla.org\":\"c002828b-d5a6-436c-8338-dbb2395e637a\",\"wikipedia@search.mozilla.org\":\"c860169d-02bb-4611-acd3-59933135b030\",\"bing@search.mozilla.org\":\"ad2033bd-a8fe-4a3c-b53b-8f986bc2796e\",\"ddg@search.mozilla.org\":\"51dc58c4-9d55-436d-97ed-4a371789756c\",\"uBlock0@raymondhill.net\":\"7bc9829e-df1d-44af-bdb7-a2f8d1e9326d\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1675362807);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "0f1989c3-10a7-4dce-a4b8-6a7bc4bda3d1");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1675362797);
user_pref("toolkit.telemetry.cachedClientID", "663c3450-4a4f-4306-9150-b6c5392a312e");
user_pref("toolkit.telemetry.previousBuildID", "20230131151141");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
