Net/ThemeName "Catppuccin-Mocha-BL"
Net/IconThemeName "Tela-purple-dark"
Gtk/CursorThemeName "Fluent-dark-cursors"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
