# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

theme = "catppuccin-mocha"

[servers.liberachat]
nickname = "halloy9819"
server = "irc.libera.chat"
channels = ["#halloy"]
