---
unpack:
    -   source: /run/rootfsbase
        sourcefs: ext3
        destination: ""
        exclude:
            - "etc/motd"
            - "etc/issue"
            - "etc/sddm.conf"
            - "etc/calamares"
            - "etc/sudoers.d/99-lazylinux-live"
            - "etc/skel/Desktop/calamares.desktop"
            - "home/anon"
            - "usr/bin/lazy-installer"
            - "usr/sbin/lazy-installer"
            - "var/cache/xbps"
