## System commands
alias _='sudo'
alias tarnow='tar -acf'
alias untar='tar -zxvf'
alias wget='wget -c'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias upg='topgrade --disable git_repos'
## Improved commands
alias du='dust'
alias grep='rg'
alias cat='bat'
alias ls='exa --icons'
## XBPS
alias xu='sudo xbps-install -u xbps && sudo xbps-install -Suv'
alias xin='sudo xbps-install'
alias xr='sudo xbps-remove -Rcon'
alias xl='xbps-query -l'
alias xf='xl | grep'
alias xs='xbps-query -Rs'
alias xd='xbps-query -x'
alias clrk='sudo vkpurge rm all && sudo rm -rf /var/cache/xbps/*'
## Flatpak
alias fu='flatpak update'
alias fin='flatpak install'
alias ff='flatpak repair'
alias fs='flatpak search'
alias fl='flatpak list'
alias fud='flatpak uninstall --delete-data'
alias fuu='flatpak uninstall –-unused'
## Nix
alias nu='nix-env -u'
alias nf='nix-env --query'
alias na='nix-env --query "*"'
alias ni='nix-env -i'
alias nr='nix-env -e'
alias ns='nix search'
alias no='nix-env --rollback'
alias ncl='nix-channel --list'
alias nca='nix-channel --add'
alias ncu='nix-channel --update'
## System Controls
alias halt='sudo halt'
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown'
